### ISSUE TITLE
Blurred shadow outside window frame

### ISSUE THREAD

**Issue by Azarattum** [Peticali/PythonBlurBehind#3]
The window shadow gets blurred too. That does not look nice at all. Is there a way to fix that or disable the shadow? `Qt.NoDropShadowWindowHint` has no effect.

![image](https://user-images.githubusercontent.com/43073346/133196031-2d367bba-d0f7-4cea-8c80-23b8c7834c88.png)

Code used:
```python
import sys
from PySide6.QtWidgets import *
from PySide6.QtCore import *
from BlurWindow.blurWindow import GlobalBlur

class MainWindow(QWidget):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.resize(500, 400)

        GlobalBlur(self.winId(), Dark=True, Acrylic=True, QWidget=self)
        self.setStyleSheet("background-color: rgba(0, 0, 0, 0)")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mw = MainWindow()
    mw.show()
    sys.exit(app.exec())

```

**Comment by Peticali** [comment]
it's a windows 10 bug, in windows 11 it was fixed, a workaround to remove this edge is to use the Frameless Window flag

```
import sys
from PySide6.QtWidgets import *
from PySide6.QtCore import *
from BlurWindow.blurWindow import GlobalBlur

class MainWindow(QWidget):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.setWindowFlags(Qt.FramelessWindowHint) #Here
        self.resize(500, 400)

        GlobalBlur(self.winId(), Dark=True, Acrylic=True, QWidget=self)
        self.setStyleSheet("background-color: rgba(0, 0, 0, 0)")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mw = MainWindow()
    mw.show()
    sys.exit(app.exec())
```

![image](https://user-images.githubusercontent.com/34588988/133303155-e8ab031e-655d-4da5-968c-e8f78c136e39.png)

**Comment by HRudyPlayZ** [comment]
Could you look at fixing it by looking at what similar softwares do? 
For example, there's this library for Electron apps that creates blur behind a window without having the blurred window shadow: https://github.com/NyaomiDEV/Glasstron

**Comment by Peticali** [comment]
> Could you look at fixing it by looking at what similar softwares do? For example, there's this library for Electron apps that creates blur behind a window without having the blurred window shadow: https://github.com/NyaomiDEV/Glasstron

I think the glasstron/electron activates the "frameless window flag" that fixes it, you can see for example discord has a custom title bar.
