### ISSUE TITLE
Blur causes unwanted clicks

### ISSUE THREAD

**Issue by vednig** [Peticali/PythonBlurBehind#6]
Using the blur via transparent attribute in tkinter causes clicks in empty places to not work.

**Comment by Peticali** [comment]
Blur is not solid, just a windows effect, I don't believe it's possible to make a transparent window in tkinter without the transparent attribute, but I'll do a search

**Comment by vednig** [comment]
Leaving transparent color as an empty string makes it accessible i.e. '' but  it chooses black as default an blurs out anything black. See:
![image](https://user-images.githubusercontent.com/64083352/140305130-a1258e75-e496-48ca-9a29-c73a8fb5d80c.png)
Code:

`
root.wm_attributes('-transparentcolor','')
`

**Comment by Peticali** [comment]
Sorry for the delay, I was on exam week, I searched all over tkinter and there doesn't seem to be any way to avoid these clicks (apart from removing the black color) the only way to solve it would be running win32 api functions manually to remove the background and have control over it example: https://stackoverflow.com/questions/3970066/creating-a-transparent-window-in-c-win32.
I still have a lot of things to fix in BlurWindow, but unfortunately I don't have time, maybe in the future I'll try to implement these functions, if you can, the pull request will always be waiting :)

**Comment by vednig** [comment]
See, I know one way it's by setting transparent color attribute empty like an empty string ' ' . It works but through this it accepts default color as Black. So any content in black won't appear.

**Comment by vednig** [comment]
> The easiest way to ensure that the extended frames are visible is to **paint the entire client region black**. To accomplish this, initialize the hbrBackground member of your WNDCLASS or WNDCLASSEX structure to the handle of the stock BLACK_BRUSH. The following image shows the same standard frame (left) and extended frame (right) shown previously. This time, however, hbrBackground is set to the BLACK_BRUSH handle obtained from the GetStockObject function.

After going through docs at https://docs.microsoft.com/en-us/windows/win32/dwm/customframe
