### ISSUE TITLE
Acrylic effect on widgets

### ISSUE THREAD

**Issue by Prx001** [Peticali/PythonBlurBehind#7]
Is there any way to apply the effect on a **widget** in my window?!

**Comment by Peticali** [comment]
> Is there any way to apply the effect on a **widget** in my window?!

A QT Widget or Tkinter Widget? 

Tkinter from what I've studied it's only possible to blur leaving the background of the widget transparent and the screen too, then use a frame to cover areas that don't want the blur

In QT you can use the examples that will work in a widget too.

**Comment by Prx001** [comment]
> In QT you can use the examples that will work in a widget too.

In the examples folder, you've used a QWidget as your window, then you have applied the effect.
But I actually want to apply the effect on a widget **in my window**. eg. a QPushButton, QFrame or a simple custom widget.

**Comment by Peticali** [comment]
> > In QT you can use the examples that will work in a widget too.
> 
> In the examples folder, you've used a QWidget as your window, then you have applied the effect. But I actually want to apply the effect on a widget **in my window**. eg. a QPushButton, QFrame or a simple custom widget.

Unfortunately not, you can follow my tkinter tip, make your button transparent and apply the effect to the window.
